//
//  ScrobblePresenter.swift
//  SimpleScrob
//
//  Created by Josh Freed on 9/30/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScrobblePresentationLogic {
    func presentSearchingForNewScrobbles()
    func presentSongsToScrobble(response: Scrobble.SearchForNewScrobbles.Response)
    func presentSubmittingToLastFM()
    func presentScrobblingComplete(response: Scrobble.SubmitScrobbles.Response)
    func presentScrobbleFailedNotLoggedIn()
    func presentCurrentUser(response: Scrobble.GetCurrentUser.Response)
}

class ScrobblePresenter: ScrobblePresentationLogic {
    weak var viewController: ScrobbleDisplayLogic?

    // MARK: Search for new scrobbles
    
    func presentSearchingForNewScrobbles() {
        viewController?.displaySearchingForNewScrobbles()
    }
    
    func presentSongsToScrobble(response: Scrobble.SearchForNewScrobbles.Response) {
        guard response.songs.count > 0 else {
            viewController?.displayNoSongsToScrobble()
            return
        }

        let viewModel = Scrobble.SearchForNewScrobbles.ViewModel(numberOfSongs: response.songs.count)
        viewController?.displaySongsToScrobble(viewModel: viewModel)
    }
    
    // MARK: Submit scrobbles
    
    func presentSubmittingToLastFM() {
        viewController?.displaySubmittingToLastFM()
    }
    
    func presentScrobblingComplete(response: Scrobble.SubmitScrobbles.Response) {
        var errorMsg: String?
        
        if let error = response.error {
            errorMsg = "\(error)"
        }
        
        let viewModel = Scrobble.SubmitScrobbles.ViewModel(error: errorMsg)
        viewController?.displayScrobblingComplete(viewModel: viewModel)
    }
    
    func presentScrobbleFailedNotLoggedIn() {
        viewController?.displayScrobbleFailedNotSignedIn()
    }
    
    // MARK: Get current user
    
    func presentCurrentUser(response: Scrobble.GetCurrentUser.Response) {
        let viewModel = Scrobble.GetCurrentUser.ViewModel(username: currentUserText(currentUserName: response.username))
        viewController?.displayCurrentUser(viewModel: viewModel)
    }

    // MARK: Helpers
    
    private func currentUserText(currentUserName: String?) -> String? {
        guard let currentUserName = currentUserName else {
            return nil
        }
        
        return "Signed in as \(currentUserName)"
    }
}
