//
//  ScrobbleViewController.swift
//  SimpleScrob
//
//  Created by Josh Freed on 9/30/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ScrobbleDisplayLogic: class {
    func displayAuthorized(viewModel: Scrobble.Refresh.ViewModel)
    func displayAuthorizationPrimer()
    func displayAuthorizationDenied()
    func displayScanningMusicLibrary()
    func displayLibraryScanComplete(viewModel: Scrobble.InitializeMusicLibrary.ViewModel)
    func displaySearchingForNewScrobbles()
    func displaySongsToScrobble(viewModel: Scrobble.SearchForNewScrobbles.ViewModel)
    func displayNoSongsToScrobble()
    func displaySubmittingToLastFM()
    func displayScrobblingComplete(viewModel: Scrobble.SubmitScrobbles.ViewModel)
    func displayCurrentUser(viewModel: Scrobble.GetCurrentUser.ViewModel)
}

class ScrobbleViewController: UIViewController, ScrobbleDisplayLogic {
    var interactor: ScrobbleBusinessLogic?
    var router: (NSObjectProtocol & ScrobbleRoutingLogic & ScrobbleDataPassing)?
    
    @IBOutlet weak var contentStackView: UIStackView!
    @IBOutlet weak var footerStackView: UIStackView!
    @IBOutlet weak var statusLabel: UILabel!
    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
    @IBOutlet weak var signInButton: UIButton!
    @IBOutlet weak var scrobbleCountLabel: UILabel!
    @IBOutlet weak var doneLabel: UILabel!
    @IBOutlet weak var requestAuthorizationButton: UIButton!
    @IBOutlet weak var errorLabel: UILabel!
    @IBOutlet weak var retryButton: UIButton!
    @IBOutlet weak var currentUserButton: UIButton!
    @IBOutlet weak var viewScrobblesButton: UIButton!
    @IBOutlet weak var viewScrobblesHitAreaButton: UIButton!
    
    var mediaAuthPrimerView: MediaAuthPrimerView?
    
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let appDelegate = UIApplication.shared.delegate as! AppDelegate
        let viewController = self
        let interactor = ScrobbleInteractor(
            mediaLibrary: appDelegate.mediaLibrary,
            worker: ScrobbleWorker(
                api: appDelegate.lastFM,
                database: appDelegate.database,
                session: appDelegate.session,
                songScanner: appDelegate.songScanner,
                batchUpdater: appDelegate.batchSongUpdater
            ),
            songScanner: appDelegate.songScanner
        )
        let presenter = ScrobblePresenter()
        let router = ScrobbleRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
        NotificationCenter.default.addObserver(self, selector: #selector(refresh), name: .UIApplicationWillEnterForeground, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(userSignedIn), name: .signedIn, object: nil)
        
        mediaAuthPrimerView = MediaAuthPrimerView.loadFromNib()
        mediaAuthPrimerView!.delegate = self
        contentStackView.addArrangedSubview(mediaAuthPrimerView!)
        
        requestAuthorizationButton.layer.cornerRadius = 5
        
        activityIndicator.startAnimating()
        
        refresh()
    }
    
    @objc func applicationDidBecomeActive() {
        
        refresh()
    }
    
    @objc func userSignedIn() {
        interactor?.getCurrentUser()
    }
    
    @IBAction func unwindToScrobble(segue: UIStoryboardSegue) {
        
    }
    
    @IBAction func tappedUserButton(_ sender: UIButton) {
        guard isLoggedIn else {
            return
        }
        
        displaySignOutConfirmation()
    }

    // MARK: Refresh

    @objc func refresh() {
        resetUI()
        
        let request = Scrobble.Refresh.Request()
        interactor?.refresh(request: request)
    }
    
    private func resetUI() {
        statusLabel.isHidden = true
        activityIndicator.stopAnimating()
        signInButton.isHidden = true
        currentUserButton.isHidden = true
        mediaAuthPrimerView?.isHidden = true
        doneLabel.isHidden = true
        scrobbleCountLabel.isHidden = true
        requestAuthorizationButton.isHidden = true
        errorLabel.isHidden = true
        retryButton.isHidden = true
    }
    
    func displayAuthorized(viewModel: Scrobble.Refresh.ViewModel) {
        requestAuthorizationButton.isHidden = true
        statusLabel.text = ""
        viewScrobblesButton.isHidden = false
        viewScrobblesHitAreaButton.isHidden = false
        
        if viewModel.firstTime {
            let request = Scrobble.InitializeMusicLibrary.Request()
            interactor?.initializeMusicLibrary(request: request)
        } else {
            let request = Scrobble.SearchForNewScrobbles.Request()
            interactor?.searchForNewScrobbles(request: request)
        }
    }
    
    func displayAuthorizationPrimer() {
        statusLabel.text = "SimpleScrob needs access to your music library to track the songs you play."
        statusLabel.isHidden = false
        requestAuthorizationButton.isHidden = false
        viewScrobblesButton.isHidden = true
        viewScrobblesHitAreaButton.isHidden = true
    }
    
    func displayAuthorizationDenied() {
        
    }
    
    @IBAction func tappedRequestAuthorization(_ sender: UIButton) {
        interactor?.requestMediaLibraryAuthorization()
    }
    
    // MARK: Initialize music library
    
    func displayScanningMusicLibrary() {
        statusLabel.isHidden = false
        statusLabel.text = "Scanning your music library..."
        activityIndicator.startAnimating()
    }
    
    func displayLibraryScanComplete(viewModel: Scrobble.InitializeMusicLibrary.ViewModel) {
        statusLabel.isHidden = false
        statusLabel.text = "Songs you listen to will be scrobbled next time you open the app."
        activityIndicator.stopAnimating()
    }
    
    // MARK: Search for new scrobbles
    
    func displaySearchingForNewScrobbles() {
        statusLabel.isHidden = false
        statusLabel.text = "Searching for new scrobbles..."
        activityIndicator.startAnimating()
    }
    
    func displaySongsToScrobble(viewModel: Scrobble.SearchForNewScrobbles.ViewModel) {
        scrobbleCountLabel.isHidden = false
        statusLabel.isHidden = true
        activityIndicator.stopAnimating()
        
        let message = viewModel.numberOfSongs == 1 ? "Found 1 new scrobble." : "Found \(viewModel.numberOfSongs) new scrobbles."
        scrobbleCountLabel.text = message
//
        let request = Scrobble.SubmitScrobbles.Request()
        interactor?.submitScrobbles(request: request)
    }
    
    func displayNoSongsToScrobble() {
        statusLabel.text = "No songs to scrobble."
        activityIndicator.stopAnimating()
    }
    
    // MARK: Submit scrobbles
    
    @IBAction func tappedRetry(_ sender: UIButton) {
        let request = Scrobble.SubmitScrobbles.Request()
        self.interactor?.submitScrobbles(request: request)
    }
    
    func displaySubmittingToLastFM() {
        retryButton.isHidden = true
        errorLabel.isHidden = true
        statusLabel.isHidden = false
        activityIndicator.startAnimating()
        statusLabel.text = "Submitting to last.fm..."
    }
    
    func displayScrobblingComplete(viewModel: Scrobble.SubmitScrobbles.ViewModel) {
        if let error = viewModel.error {
            activityIndicator.stopAnimating()
            errorLabel.text = error
            retryButton.isHidden = false
            errorLabel.isHidden = false
        } else {
            doneLabel.isHidden = false
            activityIndicator.stopAnimating()
        }        
    }
    
    // MARK: Get current user
    
    var isLoggedIn = false
    
    func displayCurrentUser(viewModel: Scrobble.GetCurrentUser.ViewModel) {
        if let username = viewModel.username {
            isLoggedIn = true
            currentUserButton.isHidden = false
            signInButton.isHidden = true
        } else {
            isLoggedIn = false
            currentUserButton.isHidden = true
            signInButton.isHidden = false
            signInButton.alpha = 0
            UIView.animate(withDuration: 0.25, animations: {
                self.signInButton.alpha = 1
            })
        }
    }
    
    // MARK: Sign Out
    
    func displaySignOutConfirmation() {
        let activitySheet = UIAlertController(title: "Sign Out of Last.fm?", message: nil, preferredStyle: .actionSheet)
        activitySheet.addAction(UIAlertAction(title: "Sign Out", style: .destructive, handler: { action in
            self.signOut()
        }))
        activitySheet.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
        
        let popoverPresenter = activitySheet.popoverPresentationController
        popoverPresenter?.sourceView = currentUserButton
        popoverPresenter?.sourceRect = currentUserButton.bounds
        
        present(activitySheet, animated: true, completion: nil)
    }
    
    func signOut() {
        let request = Scrobble.SignOut.Request()
        interactor?.signOut(request: request)
    }
}

extension ScrobbleViewController: MediaAuthPrimerViewDelegate {
    func authorizationWasGranted() {
//        refresh()
    }
    
    func authorizationWasDenied() {
//        refresh()
    }
}
