//
//  ScrobbleModels.swift
//  SimpleScrob
//
//  Created by Josh Freed on 9/30/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Scrobble {
    // MARK: Use cases

    enum Refresh {

        struct Request {
        }

        struct Response {
            var currentUserName: String?
            var songs: [Song]?
        }

        struct ViewModel {
            var currentUserName: String?
        }

    }

}
