//
//  SignInModels.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/2/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SignIn {
    // MARK: Use cases

    enum SignIn {

        struct Request {
            let username: String
            let password: String
        }

        struct Response {
            let error: SignInError?
        }

        struct ViewModel {
            let error: String?
        }

    }

}
