//
//  SignInWorker.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/2/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SignInWorker {
    let lastFM: LastFMAPI
    let session: Session
    
    init(lastFM: LastFMAPI, session: Session) {
        self.lastFM = lastFM
        self.session = session
    }
    
    func signIn(username: String, password: String, completion: @escaping (_ success: Bool) -> ()) {
        lastFM.getMobileSession(username: username, password: password) { result in
            switch result {
            case .success(let session):
                self.session.start(sessionKey: session.key, username: username)                
                completion(true)
            case .failure:
                completion(false)
            }
        }
    }
}
