//
//  ViewScrobblesModels.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/8/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ViewScrobbles {
    // MARK: Use cases

    enum GetScrobbleHistory {
        struct Request {
        }

        struct Response {
            let scrobbles: [PlayedSong]
        }

        struct ViewModel {
            let scrobbles: [PlayedSong]
        }
    }
}
