//
//  ViewScrobblesInteractor.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/8/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewScrobblesBusinessLogic {
    func getScrobbleHistory(request: ViewScrobbles.GetScrobbleHistory.Request)
}

protocol ViewScrobblesDataStore {
    
}

class ViewScrobblesInteractor: ViewScrobblesBusinessLogic, ViewScrobblesDataStore {
    var presenter: ViewScrobblesPresentationLogic?
    var worker: ViewScrobblesWorker?

    // MARK: Get scrobble history

    func getScrobbleHistory(request: ViewScrobbles.GetScrobbleHistory.Request) {
        worker?.getScrobbleHistory { songs in            
            DispatchQueue.main.async {
                let response = ViewScrobbles.GetScrobbleHistory.Response(scrobbles: songs)
                self.presenter?.presentSomething(response: response)
            }
        }
    }
}
