//
//  ViewScrobblesInteractor.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/8/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewScrobblesBusinessLogic {
    func getScrobbleHistory(request: ViewScrobbles.GetScrobbleHistory.Request)
    func loadMore(request: ViewScrobbles.LoadMore.Request)
}

protocol ViewScrobblesDataStore {
    
}

class ViewScrobblesInteractor: ViewScrobblesBusinessLogic, ViewScrobblesDataStore {
    var presenter: ViewScrobblesPresentationLogic?
    var worker: ViewScrobblesWorker?

    private var songs: [PlayedSong] = []
    
    // MARK: Get scrobble history

    func getScrobbleHistory(request: ViewScrobbles.GetScrobbleHistory.Request) {
        worker?.getScrobbleHistory { songs in
            self.songs = songs
            
            DispatchQueue.main.async {
                let response = ViewScrobbles.GetScrobbleHistory.Response(scrobbles: songs, reachedEndOfItems: false)
                self.presenter?.presentScrobbleHistory(response: response)
            }
        }
    }
    
    func loadMore(request: ViewScrobbles.LoadMore.Request) {
        worker?.loadMoreScrobbles(skip: songs.count) { (songs, reachedEndOfItems) in
            self.songs.append(contentsOf: songs)
            
            DispatchQueue.main.async {
                let response = ViewScrobbles.GetScrobbleHistory.Response(scrobbles: self.songs, reachedEndOfItems: reachedEndOfItems)
                self.presenter?.presentScrobbleHistory(response: response)
            }
        }
    }
}
