//
//  ViewScrobblesWorker.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/8/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewScrobblesArtworkFetcher {
    func artwork(for persistentId: MediaEntityPersistentId) -> MediaItemArtwork?
}

protocol GetRecentScrobbles {
    func getRecentScrobbles(completion: @escaping ([PlayedSong]) -> ())
}

class ViewScrobblesWorker {
    let database: GetRecentScrobbles
    let artworkService: ViewScrobblesArtworkFetcher
    
    init(database: GetRecentScrobbles, artworkService: ViewScrobblesArtworkFetcher) {
        self.database = database
        self.artworkService = artworkService
    }
    
    func getScrobbleHistory(completion: @escaping ([PlayedSong]) -> ()) {
        database.getRecentScrobbles { scrobbles in
            var scrobblesWithArtwork = scrobbles
            for i in 0..<scrobblesWithArtwork.count {
                scrobblesWithArtwork[i].artwork = self.artworkService.artwork(for: scrobblesWithArtwork[i].persistentId)
            }
            completion(scrobblesWithArtwork)
        }
    }
}
