//
//  ViewScrobblesWorker.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/8/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ViewScrobblesWorker {
    let database: Database
    let mediaLibrary: MediaLibrary
    
    init(database: Database, mediaLibrary: MediaLibrary) {
        self.database = database
        self.mediaLibrary = mediaLibrary
    }
    
    func getScrobbleHistory(completion: @escaping ([PlayedSong]) -> ()) {
        database.getRecentScrobbles { scrobbles in
            var scrobblesWithArtwork = scrobbles
            for i in 0..<scrobblesWithArtwork.count {
                scrobblesWithArtwork[i].artwork = self.mediaLibrary.artwork(for: scrobblesWithArtwork[i].persistentId)
            }
            completion(scrobblesWithArtwork)
        }
    }
}
