//
//  ViewScrobblesPresenter.swift
//  SimpleScrob
//
//  Created by Josh Freed on 10/8/17.
//  Copyright (c) 2017 Josh Freed. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewScrobblesPresentationLogic {
    func presentSomething(response: ViewScrobbles.GetScrobbleHistory.Response)
}

class ViewScrobblesPresenter: ViewScrobblesPresentationLogic {
    weak var viewController: ViewScrobblesDisplayLogic?

    // MARK: Do something

    func presentSomething(response: ViewScrobbles.GetScrobbleHistory.Response) {
        let viewModel = ViewScrobbles.GetScrobbleHistory.ViewModel(scrobbles: response.scrobbles)
        viewController?.displaySomething(viewModel: viewModel)
    }
}
